inference: false

model:

  class_name: fsm.model.model_4dlvsm.FSM4DLVSM
  patch_size: 8
  dim: 768
  num_layers: 24
  max_frames: 256

  plucker_repr:
    - ray_o
    - ray_d
    - o_cross_d
    # - nearest_pts

  image_tokenizer:

    image_size: 256

  block_config:

    - type: fsm.model.model_blocks.SelfAttention
      length_dim: l
      params:
        head_dim: 64
        use_qk_norm: true

    - type: fsm.model.model_lacet.FastWeightGluMLPMultihead
      length_dim: vl
      params:
        head_dim: 768
        inter_multi: 2
        base_lr: 0.01
        muon_update_steps: 5
        chunk_size: 8192

    - type: fsm.model.model_blocks.MLP
      length_dim: vl
      params:
        inter_multi: 4

training:
  
  reset_optim: true

  # general config
  use_hop: true               # running on H100 / ... 
  use_amp: false              # running on A100 / ... automatic mixed precision
  use_tf32: true
  amp_dtype: "bf16"
  torch_compile: false
  actckpt: true

  # data loader
  pin_memory: true
  bs_per_gpu: 4
  num_workers: 8
  base_world_size: 8
  num_threads: 32
  prefetch_factor: 4
  
  # view sampling
  num_all_views: 64
  num_input_views: 32
  num_target_views: 32

  # loss weights
  l2_loss_weight: 1.0
  lpips_loss_weight: 0.5
  perceptual_loss_weight: 0.0
  ssim_loss_weight: 0.0
  pixelalign_loss_weight: 0.0
  pointsdist_loss_weight: 0.0

  # optimization and scheduling
  weight_decay: 0.05
  lr: 5e-5
  betas: [0.9, 0.95]
  steps: 20000
  warmup_steps: 1000
  l2_warmup_steps: 500
  pointsdist_warmup_steps: 0

  # ewc parameters
  ewc_enable: true                    # enable Elastic Weight Consolidation (EWC)
  ewc_lambda_prox: 0.5                # proximal strength applied inside LaCT
  ewc_alpha: 0.5                      # EMA factor for Fisher information in-stream
  ewc_mode: "si"                      # Fisher proxy mode: "sq" = Δw², "abs" = |Δw|
  ewc_anchor_policy: "streaming-ema"  # anchor update strategy: "global", "streaming" + "(-online)" "(-ema)"
  ewc_anchor_beta: 0.5                # EMA factor for anchor update if using ema-streaming policy5  
  ewc_loss_weight: 0.0                # training-time EWC loss weight (0.0 = off)

  # gradient accumulation and clipping
  grad_clip_warmup_steps: 1000
  grad_accum_steps: 1                 # [TODO]: add support for gradient accumulation
  grad_clip_norm: 1.0
  grad_threshold: 4.0
  grad_checkpoint_every: 1

  # logging and saving
  log_every: 100                      # log metrics every fwdbwd_pass steps
  visualize_every: 1000               # save pth after every fwdbwd_pass steps
  save_every: 1000                    # save pth after every fwdbwd_pass steps

dataset:

  window_size: 256
  sort_by_time: true

  scene_pose_normalize: true
  dataset_ratios:
    multicam: 4
    stereo4d: 2
    dynamic_replica: 100
    spring: 500
    point_odyssey: 200
    re10k: 1
    dl3dv: 1

wandb:

  wandb_entity: "fast_spatial_memory"
  wandb_project: "fsm_finetune_256"
  wandb_name: "fsm_finetune_lvsm_256"
  wandb_mode: "online"
